-- 1. Create the images table (if not exists)
create table if not exists public.images (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  url text not null,
  category text not null
);

-- 2. Enable Row Level Security (RLS)
alter table public.images enable row level security;

-- 3. Create Policy: Allow everyone to view images
drop policy if exists "Public images are viewable by everyone" on public.images;
create policy "Public images are viewable by everyone"
  on public.images for select
  using ( true );

-- 4. Create Policy: Allow uploads
drop policy if exists "Enable insert for everyone" on public.images;
create policy "Enable insert for everyone"
  on public.images for insert
  with check ( true );

-- 5. Create Policy: Allow delete images (New)
drop policy if exists "Enable delete for everyone" on public.images;
create policy "Enable delete for everyone"
  on public.images for delete
  using ( true );

-- 6. Storage Setup
insert into storage.buckets (id, name, public)
values ('portfolio', 'portfolio', true)
on conflict (id) do nothing;

-- 7. Storage Policies
drop policy if exists "Public Access" on storage.objects;
create policy "Public Access"
  on storage.objects for select
  using ( bucket_id = 'portfolio' );

drop policy if exists "Public Upload" on storage.objects;
create policy "Public Upload"
  on storage.objects for insert
  with check ( bucket_id = 'portfolio' );

-- 8. Storage Delete Policy (New)
drop policy if exists "Public Delete" on storage.objects;
create policy "Public Delete"
  on storage.objects for delete
  using ( bucket_id = 'portfolio' );

-- 9. Create messages table (if not exists)
create table if not exists public.messages (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null,
  email text not null,
  subject text not null,
  message text not null
);

-- 10. Enable RLS for messages
alter table public.messages enable row level security;

-- 11. Allow public inserts for messages
drop policy if exists "Enable insert for everyone" on public.messages;
create policy "Enable insert for everyone"
  on public.messages for insert
  with check ( true );

-- 12. Allow public read for messages
drop policy if exists "Enable select for everyone" on public.messages;
create policy "Enable select for everyone"
  on public.messages for select
  using ( true );

-- 13. Allow public delete for messages
drop policy if exists "Enable delete for everyone" on public.messages;
create policy "Enable delete for everyone"
  on public.messages for delete
  using ( true );

-- 14. Create section_covers table (New)
create table if not exists public.section_covers (
  section_id text primary key,
  image_url text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 15. Enable RLS for section_covers
alter table public.section_covers enable row level security;

-- 16. Allow public read for section_covers
drop policy if exists "Enable select for everyone" on public.section_covers;
create policy "Enable select for everyone"
  on public.section_covers for select
  using ( true );

-- 17. Allow authenticated (or public for now) all for section_covers
drop policy if exists "Enable all for everyone" on public.section_covers;
create policy "Enable all for everyone"
  on public.section_covers for all
  using ( true )
  with check ( true );

-- 18. Create testimonials table (Client Feedback)
create table if not exists public.testimonials (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null,
  event text not null,
  feedback text not null,
  location text
);

-- 19. Enable RLS for testimonials
alter table public.testimonials enable row level security;

-- 20. Allow public read for testimonials
drop policy if exists "Enable select for everyone" on public.testimonials;
create policy "Enable select for everyone"
  on public.testimonials for select
  using ( true );

-- 21. Allow public insert for testimonials (admin page uses anon key)
drop policy if exists "Enable insert for everyone" on public.testimonials;
create policy "Enable insert for everyone"
  on public.testimonials for insert
  with check ( true );

-- 22. Allow public delete for testimonials (admin page uses anon key)
drop policy if exists "Enable delete for everyone" on public.testimonials;
create policy "Enable delete for everyone"
  on public.testimonials for delete
  using ( true );
