-- 1. Create the images table (if not exists)
create table if not exists public.images (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  url text not null,
  category text not null
);

-- 2. Enable Row Level Security (RLS)
alter table public.images enable row level security;

-- 3. Create Policy: Allow everyone to view images
drop policy if exists "Public images are viewable by everyone" on public.images;
create policy "Public images are viewable by everyone"
  on public.images for select
  using ( true );

-- 4. Create Policy: Allow uploads
drop policy if exists "Enable insert for everyone" on public.images;
create policy "Enable insert for everyone"
  on public.images for insert
  with check ( true );

-- 5. Create Policy: Allow delete images (New)
drop policy if exists "Enable delete for everyone" on public.images;
create policy "Enable delete for everyone"
  on public.images for delete
  using ( true );

-- 6. Storage Setup
insert into storage.buckets (id, name, public)
values ('portfolio', 'portfolio', true)
on conflict (id) do nothing;

-- 7. Storage Policies
drop policy if exists "Public Access" on storage.objects;
create policy "Public Access"
  on storage.objects for select
  using ( bucket_id = 'portfolio' );

drop policy if exists "Public Upload" on storage.objects;
create policy "Public Upload"
  on storage.objects for insert
  with check ( bucket_id = 'portfolio' );

-- 8. Storage Delete Policy (New)
drop policy if exists "Public Delete" on storage.objects;
create policy "Public Delete"
  on storage.objects for delete
  using ( bucket_id = 'portfolio' );

-- 9. Create messages table (if not exists)
create table if not exists public.messages (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null,
  email text not null,
  subject text not null,
  message text not null
);

-- 10. Enable RLS for messages
alter table public.messages enable row level security;

-- 11. Allow public inserts for messages
drop policy if exists "Enable insert for everyone" on public.messages;
create policy "Enable insert for everyone"
  on public.messages for insert
  with check ( true );

-- 12. Allow public read for messages
drop policy if exists "Enable select for everyone" on public.messages;
create policy "Enable select for everyone"
  on public.messages for select
  using ( true );

-- 13. Allow public delete for messages
drop policy if exists "Enable delete for everyone" on public.messages;
create policy "Enable delete for everyone"
  on public.messages for delete
  using ( true );
